### ISSUE TITLE
Deterministic pod naming

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#120]
I'd love to have a consistent naming of pods.

Currently, pod names are composed out of `fullname-<random generated sequence>`, e.g. for RSC (when setting `fullnameOverride: rsc`:

```
rsc-597764dd85-5rz59
```

When describing the status of a certain pod, I first need to query the exact pod name to be able to describe it afterwards.

What I would like to achieve would be something like

```
rsc-0
rsc-1
rsc-2
```

This would make it possible to re-use old commands and to remember the pod names at some point.

Maybe this is even already possible and I overlooked how to do it?

**Comment by d-m** [comment]
Hey @pat-s, this is more of a function of how Kubernetes `Deployment` resources are managed. A Kubernetes `Deployment` always adds a random identifier to the end of the pod name.

The naming behavior you're looking can be obtained using a Kubernetes `StatefulSet` resource, however these are generally used for stateful workloads where each pod requires a strong individual identity--for example, shards of a database where each shard is distinct and not interchangeable with one another. There are also some [limitations](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations) of `StatefulSet` resources, particularly around volumes and lifecycle, that wouldn't make them a good fit here.

If you're looking to be able to reuse `kubectl` commands then I'd recommend using labels instead of the pod name. Each Helm deployment adds a few standard labels to pods and other resources managed by the chart. You can see these with `kubectl get pods --show-labels`. For example, the `app.kubernetes.io/instance` label is applied to each resource with the value of the Helm deployment name you chose. You could get the logs for all of your pods in the Helm deployment with:

```
Kubectl get logs -l app.kubernetes.io/instance=<my release name>
```

**Comment by pat-s** [comment]
> however these are generally used for stateful workloads where each pod requires a strong individual identity--for example, shards of a database where each shard is distinct and not interchangeable with one another.

Thanks, good to know!

> You could get the logs for **all of your pods** in the Helm deployment 

Thanks, I currently do this by making use of the distinct namespace using `-n <namespace>` which seems to do the same.

However, often enough I only want to look at one pod but judging from your comment this does not seem to be easily possible by design in k8s.

I am closing here then since my Q was answered - thanks a lot for sharing this information!

**Comment by atheriel** [comment]
Another common approach here is to use a label to give deployment-created pods a consistent identity. You can then query them with e.g. `kubectl describe pods -l app=rsc`. I believe the Helm chart already sets a few labels of this kind, and you can add your own as well.
